const express = require("express");
const News = require("../models/News");
const { requireSession } = require("../middleware/sessionAuth");

const router = express.Router();

// Middleware: Admin Only
function requireAdmin(req, res, next) {
  if (req.session?.user?.role !== "admin") {
    return res.status(403).json({ ok: false, message: "Only admin allowed" });
  }
  next();
}

// 1. GET ALL NEWS (Aggregates manual News + live TournamentUpdates)
router.get("/all", async (req, res) => {
  try {
    const isAdmin = req.session?.user?.role === "admin";
    const filter = isAdmin ? {} : { status: "published" };
    
    // A. Fetch manual news
    const manualNews = await News.find(filter)
      .populate("authorId", "playerName organiserName companyName")
      .populate("tournamentId", "title course")
      .sort({ createdAt: -1 })
      .lean();

    // B. Fetch live TournamentUpdates (public only)
    const TournamentUpdate = require("../models/TournamentUpdate");
    const tUpdates = await TournamentUpdate.find({ visibility: "public" })
      .populate("tournamentId", "title course bannerUrl")
      .populate("authorId", "playerName organiserName")
      .sort({ createdAt: -1 })
      .limit(30)
      .lean();

    const mappedTUpdates = tUpdates.map(u => {
      let displayTitle = u.title || "Announcement";
      if (displayTitle.toLowerCase() === "announcement" && u.tournamentId?.title) {
        displayTitle = `${u.tournamentId.title} - Announcement`;
      }
      
      return {
        _id: u._id,
        title: displayTitle,
        content: u.message,
        excerpt: u.message.substring(0, 150) + "...",
        category: "Tournament Update",
        image: u.tournamentId?.bannerUrl || "",
        authorId: u.authorId,
        tournamentId: u.tournamentId,
        createdAt: u.createdAt,
        status: "published",
        isAutoGenerated: true
      };
    });

    // C. Merge and sort
    // Avoid duplicates if some were already auto-generated and saved to News
    // (We check by message content and tournamentId)
    const combined = [...manualNews];
    mappedTUpdates.forEach(u => {
      const exists = combined.some(n => 
        n.tournamentId?._id?.toString() === u.tournamentId?._id?.toString() && 
        n.content === u.content
      );
      if (!exists) combined.push(u);
    });

    combined.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
      
    res.json({ ok: true, news: combined });
  } catch (err) {
    res.status(500).json({ ok: false, message: err.message });
  }
});

// 2. CREATE NEWS (Admin only)
router.post("/create", requireSession, requireAdmin, async (req, res) => {
  try {
    const { title, content, excerpt, category, image, status } = req.body;
    
    const item = new News({
      title,
      content,
      excerpt: excerpt || content.substring(0, 150) + "...",
      category,
      image,
      status: status || "published",
      authorId: req.session.user.id
    });
    
    await item.save();
    res.json({ ok: true, item });
  } catch (err) {
    res.status(500).json({ ok: false, message: err.message });
  }
});

// 3. EDIT NEWS / UPDATE (Unified)
router.patch("/:id", requireSession, requireAdmin, async (req, res) => {
  try {
    const { id } = req.params;
    // Try News model first
    let item = await News.findByIdAndUpdate(id, req.body, { new: true });
    
    // If not found, try TournamentUpdate
    if (!item) {
      const TournamentUpdate = require("../models/TournamentUpdate");
      // Map frontend fields (title, content) to TournamentUpdate fields (title, message)
      const updateData = { ...req.body };
      if (updateData.content) updateData.message = updateData.content;
      
      item = await TournamentUpdate.findByIdAndUpdate(id, updateData, { new: true });
    }

    if (!item) return res.status(404).json({ ok: false, message: "Item not found" });
    res.json({ ok: true, update: item });
  } catch (err) {
    res.status(500).json({ ok: false, message: err.message });
  }
});

// 4. DELETE NEWS / UPDATE (Unified)
router.get("/all-debug", async (req, res) => {
  // Simple debug route to see IDs
  const n = await News.find().select("_id").lean();
  const TournamentUpdate = require("../models/TournamentUpdate");
  const u = await TournamentUpdate.find().select("_id").lean();
  res.json({ news: n, updates: u });
});

router.delete("/:id", requireSession, requireAdmin, async (req, res) => {
  try {
    const { id } = req.params;
    // Try deleting from News
    let deleted = await News.findByIdAndDelete(id);
    
    // If not found, try TournamentUpdate
    if (!deleted) {
      const TournamentUpdate = require("../models/TournamentUpdate");
      deleted = await TournamentUpdate.findByIdAndDelete(id);
    }

    if (!deleted) return res.status(404).json({ ok: false, message: "Item not found" });
    res.json({ ok: true, message: "Deleted successfully" });
  } catch (err) {
    res.status(500).json({ ok: false, message: err.message });
  }
});

// 5. SYNC LOGIC (Backfill existing updates into News)
router.post("/sync-updates", requireSession, requireAdmin, async (req, res) => {
  try {
    const TournamentUpdate = require("../models/TournamentUpdate");
    const updates = await TournamentUpdate.find().lean();
    let count = 0;

    for (const up of updates) {
      const exists = await News.exists({ tournamentId: up.tournamentId, content: up.message });
      if (!exists) {
        await News.create({
          title: up.title,
          content: up.message,
          excerpt: up.message.substring(0, 150) + "...",
          category: "Tournament Update",
          status: "published",
          authorId: up.authorId || req.session.user.id,
          isAutoGenerated: true,
          tournamentId: up.tournamentId,
          createdAt: up.createdAt
        });
        count++;
      }
    }
    res.json({ ok: true, message: `Synced ${count} items` });
  } catch (err) {
    res.status(500).json({ ok: false, message: err.message });
  }
});

module.exports = router;
