const mongoose = require("mongoose");

const NewsSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    content: { type: String, required: true },
    excerpt: { type: String, trim: true },
    
    category: { 
      type: String, 
      default: "Update",
      index: true 
    },
    
    image: { type: String, default: "" },
    
    authorId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    
    status: { 
      type: String, 
      enum: ["pending", "published"], 
      default: "published", 
      index: true 
    },
    
    isAutoGenerated: { type: Boolean, default: false },
    tournamentId: { type: mongoose.Schema.Types.ObjectId, ref: "Tournament", default: null },
    matchId: { type: mongoose.Schema.Types.ObjectId, ref: "Match", default: null },
  },
  { timestamps: true }
);

module.exports = mongoose.model("News", NewsSchema);
